add working init containers

diff --git a/charts/akaunting/templates/deployment.yaml b/charts/akaunting/templates/deployment.yaml
--- a/charts/akaunting/templates/deployment.yaml
+++ b/charts/akaunting/templates/deployment.yaml
@@ -31,6 +31,43 @@ spec:
       securityContext:
         {{- toYaml .Values.podSecurityContext | nindent 8 }}
       initContainers:
+        - name: download-configs
+          image: alpine:latest
+          command:
+            - /bin/sh
+            - -c
+            - |
+              apk add --no-cache wget && \
+              until wget -q -O /config/nginx.conf https://github.com/akaunting/docker/raw/refs/heads/master/nginx/nginx.conf && \
+                    wget -q -O /config/php.ini https://github.com/akaunting/docker/raw/refs/heads/master/files/php.ini && \
+                    wget -q -O /config/supervisord.conf https://github.com/akaunting/docker/raw/refs/heads/master/files/supervisord.conf; do
+                echo "Failed to download files, retrying in 5 seconds..." >&2
+                sleep 5
+              done
+          volumeMounts:
+            - name: config-volume
+              mountPath: /config
+        - name: download-application-files
+          image: alpine:latest
+          {{- if .Values.env }}
+          env:
+            {{- .Values.env | toYaml | nindent 12 }}
+          {{- end }}
+          command:
+            - /bin/sh
+            - -c
+            - |
+              if [ "$AKAUNTING_SETUP" == "true" ]; then
+                apk add --no-cache curl unzip && \
+                curl -Lo /tmp/akaunting.zip 'https://akaunting.com/download.php?version=latest&utm_source=docker&utm_campaign=developers' && \
+                unzip /tmp/akaunting.zip -d /var/www/html && \
+                rm -f /tmp/akaunting.zip
+              else
+                echo "Skipping application download as AKAUNTING_SETUP is not true.";
+              fi
+          volumeMounts:
+            - name: akaunting-data
+              mountPath: /var/www/html
         - name: wait-for-mariadb
           image: busybox
           command:
@@ -108,6 +145,15 @@ spec:
           volumeMounts:
             - name: akaunting-data
               mountPath: /var/www/html
+            - name: config-volume
+              mountPath: /usr/local/etc/php/php.ini
+              subPath: php.ini
+            - name: config-volume
+              mountPath: /etc/supervisor/conf.d/supervisord.conf
+              subPath: supervisord.conf
+            - name: config-volume
+              mountPath: /etc/nginx/nginx.conf
+              subPath: nginx.conf
             {{- with .Values.volumeMounts }}
             {{- toYaml . | nindent 12 }}
             {{- end }}
@@ -117,6 +163,8 @@ spec:
           persistentVolumeClaim:
             claimName: {{ if .Values.persistence.data.existingClaim }}{{ .Values.persistence.data.existingClaim }}{{- else }}{{ template "akaunting.fullname" . }}-data{{- end }}
           {{- end }}
+        - name: config-volume
+          emptyDir: {}
         {{- with .Values.volumes }}
         {{- toYaml . | nindent 8 }}
       {{- end }}
